version: '3.7'

services:
  queues_api:
    image: node:19.0.0
    container_name: "queues_api"
    command: /bin/sh -c "cd /app && npm install && node /app/app.js"
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    restart: always
    networks:
      - queue-ntwk    
  redis:
    image: redis:7.0.5-alpine
    container_name: "redis"
    hostname: "redis"
    expose:
      - 6379   
    restart: always
    networks:
      - queue-ntwk
  queue_worker:
    image: node:19.0.0
    container_name: "queue_worker"
    hostname: "queue_worker"
    command: /bin/sh -c "cd /app && npm install && node /app/worker_logic.js"
    volumes:
      - ./:/app
    depends_on:
      - redis
    networks:
      - queue-ntwk      
networks:
  queue-ntwk:
    driver: bridge
    name: queue-ntwk    